//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string CAR_FRONT_HIT = "car_front_hit";
        
        public const string UI_LEFT = "ui_left";
        
        public const string UI_RIGHT = "ui_right";
        
        public const string CAR_HIT_BACK = "car_hit_back";
        
        public const string CAR_HIT_LEFT = "car_hit_left";
        
        public const string CAR_HIT_RIGHT = "car_hit_right";
    }
}
